In [1]:
import pandas as pd

In [2]:
file_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/sample.csv'

In [3]:
sample = pd.read_csv(file_url)
sample

    Var_1  Var_2
0       1      2
1       3      4
2       2      5
3       5      6
4       3      2
5       1      1
6       2      6
7       5      7
8       6      8
9       7      4
10      7      7
11      8      3
12      9      7
13      3      9
14      2      2
15      1      3
16      2      6
17      2      4
18      3      3

In [4]:
sample.head()

   Var_1  Var_2
0      1      2
1      3      4
2      2      5
3      5      6
4      3      2

In [5]:
sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Var_1   19 non-null     int64
 1   Var_2   19 non-null     int64
dtypes: int64(2)
memory usage: 432.0 bytes

In [6]:
sample.describe()

           Var_1      Var_2
count  19.000000  19.000000
mean    3.789474   4.684211
std     2.529360   2.310667
min     1.000000   1.000000
25%     2.000000   3.000000
50%     3.000000   4.000000
75%     5.500000   6.500000
max     9.000000   9.000000

In [7]:
sample_dic = {'name':['John', 'Ann', 'Kevin'], 'age':[23,22,21]}
pd.DataFrame(sample_dic)

    name  age
0   John   23
1    Ann   22
2  Kevin   21

In [9]:
df_new = pd.DataFrame([[1,2],[3,4],[5,6],[7,8]], columns=['var_1', 'var_2'], index=['a','b','c','d'])
df_new

   var_1  var_2
a      1      2
b      3      4
c      5      6
d      7      8

In [10]:
file_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/sample_df.csv'

In [22]:
sample_df = pd.read_csv(file_url, index_col=0)
sample_df

   var_1  var_2  var_3  var_4  var_5
a      2      2      1      4      3
b      4      3      3      7      1
c      5      4      6      3      5
d      1      4      5      6      7
e      4      5      7      8      3
f      5      4      8      9      4
g      7      5      2      0      6
h      8      8      1      7      8
i      2      3      5      2      1
j      9      3      7      6      5

In [15]:
sample_df[['var_1', 'var_2']]

   var_1  var_2
a      2      2
b      4      3
c      5      4
d      1      4
e      4      5
f      5      4
g      7      5
h      8      8
i      2      3
j      9      3

In [16]:
sample_df.loc[['a','b','c']]

   var_1  var_2  var_3  var_4  var_5
a      2      2      1      4      3
b      4      3      3      7      1
c      5      4      6      3      5

In [17]:
sample_df.loc[['a','b','c'],['var_1', 'var_2']]

   var_1  var_2
a      2      2
b      4      3
c      5      4

In [19]:
sample_df.iloc[0:2, 0:2]

   var_1  var_2
a      2      2
b      4      3

In [20]:
sample.reset_index()

    index  Var_1  Var_2
0       0      1      2
1       1      3      4
2       2      2      5
3       3      5      6
4       4      3      2
5       5      1      1
6       6      2      6
7       7      5      7
8       8      6      8
9       9      7      4
10     10      7      7
11     11      8      3
12     12      9      7
13     13      3      9
14     14      2      2
15     15      1      3
16     16      2      6
17     17      2      4
18     18      3      3

In [24]:
sample_df

   var_1  var_2  var_3  var_4  var_5
a      2      2      1      4      3
b      4      3      3      7      1
c      5      4      6      3      5
d      1      4      5      6      7
e      4      5      7      8      3
f      5      4      8      9      4
g      7      5      2      0      6
h      8      8      1      7      8
i      2      3      5      2      1
j      9      3      7      6      5

In [25]:
sample_df.reset_index()

  index  var_1  var_2  var_3  var_4  var_5
0     a      2      2      1      4      3
1     b      4      3      3      7      1
2     c      5      4      6      3      5
3     d      1      4      5      6      7
4     e      4      5      7      8      3
5     f      5      4      8      9      4
6     g      7      5      2      0      6
7     h      8      8      1      7      8
8     i      2      3      5      2      1
9     j      9      3      7      6      5

In [27]:
sample_df.reset_index(drop=True)

   var_1  var_2  var_3  var_4  var_5
0      2      2      1      4      3
1      4      3      3      7      1
2      5      4      6      3      5
3      1      4      5      6      7
4      4      5      7      8      3
5      5      4      8      9      4
6      7      5      2      0      6
7      8      8      1      7      8
8      2      3      5      2      1
9      9      3      7      6      5

In [28]:
sample_df.set_index('var_1')

       var_2  var_3  var_4  var_5
var_1
2          2      1      4      3
4          3      3      7      1
5          4      6      3      5
1          4      5      6      7
4          5      7      8      3
5          4      8      9      4
7          5      2      0      6
8          8      1      7      8
2          3      5      2      1
9          3      7      6      5

In [35]:
sample_df.median()

var_1    4.5
var_2    4.0
var_3    5.0
var_4    6.0
var_5    4.5
dtype: float64

In [33]:
sample_df[['var_1']].describe()

           var_1
count  10.000000
mean    4.700000
std     2.668749
min     1.000000
25%     2.500000
50%     4.500000
75%     6.500000
max     9.000000

In [32]:
sample_df.describe()

           var_1     var_2      var_3      var_4      var_5
count  10.000000  10.00000  10.000000  10.000000  10.000000
mean    4.700000   4.10000   4.500000   5.200000   4.300000
std     2.668749   1.66333   2.592725   2.859681   2.359378
min     1.000000   2.00000   1.000000   0.000000   1.000000
25%     2.500000   3.00000   2.250000   3.250000   3.000000
50%     4.500000   4.00000   5.000000   6.000000   4.500000
75%     6.500000   4.75000   6.750000   7.000000   5.750000
max     9.000000   8.00000   8.000000   9.000000   8.000000

In [36]:
sample_df.aggregate(['sum', 'mean'])

      var_1  var_2  var_3  var_4  var_5
sum    47.0   41.0   45.0   52.0   43.0
mean    4.7    4.1    4.5    5.2    4.3

In [37]:
sample_df.sum()

var_1    47
var_2    41
var_3    45
var_4    52
var_5    43
dtype: int64

In [38]:
file_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/iris.csv'
iris = pd.read_csv(file_url)

In [39]:
iris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),class
0,6.1,3.0,4.6,1.4,versicolor
1,7.2,3.0,5.8,1.6,virginica
2,6.7,3.1,4.4,1.4,versicolor
3,6.2,2.9,4.3,1.3,versicolor
4,4.6,3.4,1.4,0.3,setosa

In [40]:
iris.groupby('class').mean()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
class,,,,
setosa,5.006,3.428,1.462,0.246
versicolor,5.936,2.770,4.260,1.326
virginica,6.588,2.974,5.552,2.026

In [41]:
iris.groupby('class').agg(['count','mean'])

           sepal length (cm)        sepal width (cm)        petal length (cm)  \
                       count   mean            count   mean             count
class
setosa                    50  5.006               50  3.428                50
versicolor                50  5.936               50  2.770                50
virginica                 50  6.588               50  2.974                50

                  petal width (cm)
             mean            count   mean
class
setosa      1.462               50  0.246
versicolor  4.260               50  1.326
virginica   5.552               50  2.026

In [42]:
sample_df

   var_1  var_2  var_3  var_4  var_5
a      2      2      1      4      3
b      4      3      3      7      1
c      5      4      6      3      5
d      1      4      5      6      7
e      4      5      7      8      3
f      5      4      8      9      4
g      7      5      2      0      6
h      8      8      1      7      8
i      2      3      5      2      1
j      9      3      7      6      5

In [43]:
sample_df[['var_1','var_2']]

   var_1  var_2
a      2      2
b      4      3
c      5      4
d      1      4
e      4      5
f      5      4
g      7      5
h      8      8
i      2      3
j      9      3

In [55]:
sample_df.loc[0:3, 0:2]

   var_1  var_2
a      2      2
b      4      3
c      5      4

In [57]:
sample_df.set_index('var_1')

       var_2  var_3  var_4  var_5
var_1
2          2      1      4      3
4          3      3      7      1
5          4      6      3      5
1          4      5      6      7
4          5      7      8      3
5          4      8      9      4
7          5      2      0      6
8          8      1      7      8
2          3      5      2      1
9          3      7      6      5

In [59]:
sample_df.agg(['sum','mean'])

      var_1  var_2  var_3  var_4  var_5
sum    47.0   41.0   45.0   52.0   43.0
mean    4.7    4.1    4.5    5.2    4.3

In [60]:
sample_df.aggregate(['sum','mean'])

      var_1  var_2  var_3  var_4  var_5
sum    47.0   41.0   45.0   52.0   43.0
mean    4.7    4.1    4.5    5.2    4.3

In [61]:
left_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/left.csv'
right_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/right.csv'

left = pd.read_csv(left_url)
right = pd.read_csv(right_url)

In [62]:
left

  key  var_1  var_2
0   a      1      1
1   b      3      2
2   c      4      4
3   d      2      3
4   e      1      0

In [63]:
right

  key  var_3  var_4
0   b      4      3
1   c      6      5
2   e      3      8
3   f      2      7
4   g      3      4

In [64]:
left.merge(right)

  key  var_1  var_2  var_3  var_4
0   b      3      2      4      3
1   c      4      4      6      5
2   e      1      0      3      8

In [72]:
left.merge(right, how='left')

  key  var_1  var_2  var_3  var_4
0   a      1      1    NaN    NaN
1   b      3      2    4.0    3.0
2   c      4      4    6.0    5.0
3   d      2      3    NaN    NaN
4   e      1      0    3.0    8.0

In [74]:
import numpy as np

In [75]:
sample_df

   var_1  var_2  var_3  var_4  var_5
a      2      2      1      4      3
b      4      3      3      7      1
c      5      4      6      3      5
d      1      4      5      6      7
e      4      5      7      8      3
f      5      4      8      9      4
g      7      5      2      0      6
h      8      8      1      7      8
i      2      3      5      2      1
j      9      3      7      6      5

In [77]:
sample_np = np.array(sample_df)
sample_np

array([[2, 2, 1, 4, 3],
       [4, 3, 3, 7, 1],
       [5, 4, 6, 3, 5],
       [1, 4, 5, 6, 7],
       [4, 5, 7, 8, 3],
       [5, 4, 8, 9, 4],
       [7, 5, 2, 0, 6],
       [8, 8, 1, 7, 8],
       [2, 3, 5, 2, 1],
       [9, 3, 7, 6, 5]], dtype=int64)

In [78]:
pd.DataFrame(sample_np)

   0  1  2  3  4
0  2  2  1  4  3
1  4  3  3  7  1
2  5  4  6  3  5
3  1  4  5  6  7
4  4  5  7  8  3
5  5  4  8  9  4
6  7  5  2  0  6
7  8  8  1  7  8
8  2  3  5  2  1
9  9  3  7  6  5

In [80]:
sample_df.columns

Index(['var_1', 'var_2', 'var_3', 'var_4', 'var_5'], dtype='object')

In [81]:
pd.DataFrame(sample_np, columns=sample_df.columns)

   var_1  var_2  var_3  var_4  var_5
0      2      2      1      4      3
1      4      3      3      7      1
2      5      4      6      3      5
3      1      4      5      6      7
4      4      5      7      8      3
5      5      4      8      9      4
6      7      5      2      0      6
7      8      8      1      7      8
8      2      3      5      2      1
9      9      3      7      6      5