In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_csv("./data/ecommerce.csv")
data

,Email,Address,Avatar,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
0,mstephenson@fernandez.com,"835 Frank Tunnel\nWrightmouth, MI 82180-9605",Violet,34.497268,12.655651,39.577668,4.082621,587.951054
1,hduke@hotmail.com,"4547 Archer Common\nDiazchester, CA 06566-8576",DarkGreen,31.926272,11.109461,37.268959,2.664034,392.204933
2,pallen@yahoo.com,"24645 Valerie Unions Suite 582\nCobbborough, D...",Bisque,33.000915,11.330278,37.110597,4.104543,487.547505
3,riverarebecca@gmail.com,"1414 David Throughway\nPort Jason, OH 22070-1220",SaddleBrown,34.305557,13.717514,36.721283,3.120179,581.852344
4,mstephens@davidson-herman.com,"14023 Rodriguez Passage\nPort Jacobville, PR 3...",MediumAquaMarine,33.330673,12.795189,37.536653,4.446308,599.406092
...,...,...,...,...,...,...,...,...
495,lewisjessica@craig-evans.com,"4483 Jones Motorway Suite 872\nLake Jamiefurt,...",Tan,33.237660,13.566160,36.417985,3.746573,573.847438
496,katrina56@gmail.com,"172 Owen Divide Suite 497\nWest Richard, CA 19320",PaleVioletRed,34.702529,11.695736,37.190268,3.576526,529.049004
497,dale88@hotmail.com,"0787 Andrews Ranch Apt. 633\nSouth Chadburgh, ...",Cornsilk,32.646777,11.499409,38.332576,4.958264,551.620145
498,cwilson@hotmail.com,"680 Jennifer Lodge Apt. 808\nBrendachester, TX...",Teal,33.322501,12.391423,36.840086,2.336485,456.469510
499,hannahwilson@davidson.com,49791 Rachel Heights Apt. 898\nEast Drewboroug...,DarkMagenta,33.715981,12.418808,35.771016,2.735160,497.778642

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Email                 500 non-null    object
 1   Address               500 non-null    object
 2   Avatar                500 non-null    object
 3   Avg. Session Length   500 non-null    float64
 4   Time on App           500 non-null    float64
 5   Time on Website       500 non-null    float64
 6   Length of Membership  500 non-null    float64
 7   Yearly Amount Spent   500 non-null    float64
dtypes: float64(5), object(3)
memory usage: 31.4+ KB

In [5]:
data.describe()

,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
count,500.000000,500.000000,500.000000,500.000000,500.000000
mean,33.053194,12.052488,37.060445,3.533462,499.314038
std,0.992563,0.994216,1.010489,0.999278,79.314782
min,29.532429,8.508152,33.913847,0.269901,256.670582
25%,32.341822,11.388153,36.349257,2.930450,445.038277
50%,33.082008,11.983231,37.069367,3.533975,498.887875
75%,33.711985,12.753850,37.716432,4.126502,549.313828
max,36.139662,15.126994,40.005182,6.922689,765.518462

In [15]:
data.columns[3:]

Index(['Avg. Session Length', 'Time on App', 'Time on Website',
       'Length of Membership', 'Yearly Amount Spent'],
      dtype='object')

In [20]:
data.describe().loc['75%', 'Avg. Session Length']

33.711985023954476

In [ ]:
data.describe().loc['75%', 'Avg. Session Length']

In [21]:
data.describe().loc['25%', 'Avg. Session Length']

32.34182200451778

In [24]:
d = data.describe()
a = [1.5*(d.loc['75%', i] - d.loc['25%', i]) + d.loc['75%', i] for i in data.columns[3:]]
a

[35.767229553109516,
 14.802394229583687,
 39.76719469493466,
 5.920580296370714,
 705.7271533863172]

In [26]:
b = [d.loc['25%', i] - 1.5*(d.loc['75%', i] - d.loc['25%', i]) for i in data.columns[3:]]
b

[30.286577475362737,
 9.33960882513129,
 34.29849491039147,
 1.136371357955959,
 288.6249512402365]

In [28]:
data[]

,Email,Address,Avatar,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
154,nathan86@hotmail.com,"748 Michael Plaza\nWest Billyside, UT 20799",MidnightBlue,36.139662,12.050267,36.959643,3.864861,595.803819
390,michaelcampbell@yahoo.com,"96480 White Lane Suite 521\nPattersonhaven, OR...",Gray,35.860237,11.730661,36.882149,3.416210,546.556667

In [39]:
data.iloc[154, 3] = 35.767229553109516
data.iloc[154, 3]

35.767229553109516

In [41]:
data.iloc[390, 3] = 35.767229553109516
data.iloc[390, 3]

35.767229553109516

In [42]:
data[data['Avg. Session Length'] < 30.286577475362737]

,Email,Address,Avatar,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
12,knelson@gmail.com,"6705 Miller Orchard Suite 186\nLake Shanestad,...",RoyalBlue,29.532429,10.961298,37.420216,4.046423,408.640351

In [44]:
data.iloc[12, 3] = 30.286577475362737
data.iloc[12, 3]

30.286577475362737

In [45]:
data[data['Time on App'] > 14.802394229583687]

,Email,Address,Avatar,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
65,kyang@diaz.org,"223 Love Trail Suite 831\nPort Jeffrey, IN 46849",OliveDrab,34.374258,15.126994,37.157624,5.377594,765.518462

In [47]:
data.iloc[65, 4] = 14.802394229583687
data.iloc[65, 4]

14.802394229583687

In [48]:
data[data['Time on App'] < 9.33960882513129]

,Email,Address,Avatar,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
309,dblair@gmail.com,"190 Kelley Burg\nWest Juliaport, IA 35826-8163",MediumSlateBlue,34.102279,8.508152,35.462400,1.838211,302.189548
362,cruiz@yahoo.com,"497 Julian Brook Suite 872\nHillberg, FM 87927...",LightSalmon,33.981006,9.316289,36.914952,2.868428,384.326057
442,martinkristi@sanchez-coleman.com,"PSC 1893, Box 7023\nAPO AA 73445",Lime,34.083663,8.668350,35.906756,2.252446,308.527747

In [55]:
data.iloc[309, 4], data.iloc[362, 4], data.iloc[442, 4] = 9.33960882513129, 9.33960882513129, 9.33960882513129
data.iloc[309, 4], data.iloc[362, 4], data.iloc[442, 4]

(9.33960882513129, 9.33960882513129, 9.33960882513129)

In [56]:
data[data['Time on Website'] > 39.76719469493466]

,Email,Address,Avatar,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
69,davisrobert@hicks-smith.com,"95967 Pitts Burgs\nWest Sarah, MH 27817-5147",SkyBlue,32.1791,11.187539,40.005182,3.55265,451.575685

In [57]:
data.iloc[69, 5] = 39.76719469493466
data.iloc[69, 5]

39.76719469493466

In [58]:
data[data['Time on Website'] < 34.29849491039147]

,Email,Address,Avatar,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
157,asilva@yahoo.com,USNV Johnson\nFPO AP 19026,Wheat,34.603311,12.207298,33.913847,6.922689,744.221867

In [59]:
data.iloc[157, 5] = 34.29849491039147
data.iloc[157, 5]

34.29849491039147

In [60]:
data[data['Length of Membership'] > 5.920580296370714]

,Email,Address,Avatar,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
50,william82@gmail.com,"11143 Park Squares\nSamanthatown, UT 97073",SandyBrown,33.256335,13.858062,37.780265,5.976768,725.584814
151,alicia85@lee.com,"14220 Carla Flat Suite 521\nLake Matthew, DE 0...",DimGray,32.887105,12.387184,37.431159,6.401229,684.163431
153,ebrown@osborne.com,"4291 Nichols Fork Apt. 562\nThomaschester, SC ...",DarkSlateGray,31.945396,12.965761,36.966389,6.076654,657.019924
157,asilva@yahoo.com,USNV Johnson\nFPO AP 19026,Wheat,34.603311,12.207298,34.298495,6.922689,744.221867
396,waltonkaren@gmail.com,"355 Villegas Isle Apt. 070\nWest Jenniferview,...",Green,35.742670,10.889828,35.565436,6.115199,669.987141

In [61]:
data.iloc[50, 6], data.iloc[151, 6], data.iloc[153, 6], data.iloc[157, 6], data.iloc[396, 6] = 5.920580296370714, 5.920580296370714, 5.920580296370714, 5.920580296370714, 5.920580296370714
data.iloc[50, 6], data.iloc[151, 6], data.iloc[153, 6], data.iloc[157, 6], data.iloc[396, 6]

(5.920580296370714,
 5.920580296370714,
 5.920580296370714,
 5.920580296370714,
 5.920580296370714)

In [62]:
data[data['Length of Membership'] < 1.136371357955959]

,Email,Address,Avatar,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
161,stevenking@patterson.com,"94730 Martin Mount\nNew Matthew, VI 08142-6708",LightGray,33.503705,12.399436,35.012806,0.968622,357.591439
173,fischermonica@gmail.com,9847 Michael Plaza Suite 837\nLake Christopher...,Navy,32.529769,11.747732,36.939882,0.801516,298.762008
225,alexandra26@summers-davis.com,Unit 7032 Box 7016\nDPO AE 44749-2992,Navy,32.836941,10.256549,36.143908,0.789520,256.670582
303,brandon77@richardson.com,"109 Jessica Manor\nNorth Patriciashire, PR 84726",GhostWhite,30.816201,11.851399,36.925043,1.084585,266.086341
379,tsmith@yahoo.com,"92028 Thomas Mountains Suite 044\nNew Matthew,...",Bisque,33.971722,12.284467,38.295725,1.130477,385.095007
434,jordandavid@gmail.com,"61502 Parker Vista Apt. 363\nJonesshire, GU 33532",Violet,33.666616,10.985764,36.352503,0.936498,304.135592
447,sharongraves@yahoo.com,"73098 Ronald Port\nCliffordborough, MO 37479-9244",Wheat,32.904854,12.556108,37.805509,0.269901,314.438518

In [63]:
data.iloc[161, 6], data.iloc[173, 6], data.iloc[225, 6], data.iloc[303, 6], data.iloc[379, 6], data.iloc[434, 6], data.iloc[447, 6] = 1.136371357955959, 1.136371357955959, 1.136371357955959, 1.136371357955959, 1.136371357955959, 1.136371357955959, 1.136371357955959
data.iloc[161, 6], data.iloc[173, 6], data.iloc[225, 6], data.iloc[303, 6], data.iloc[379, 6], data.iloc[434, 6], data.iloc[447, 6]

(1.136371357955959,
 1.136371357955959,
 1.136371357955959,
 1.136371357955959,
 1.136371357955959,
 1.136371357955959,
 1.136371357955959)

In [64]:
data[data['Yearly Amount Spent'] > 705.7271533863172]

,Email,Address,Avatar,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
50,william82@gmail.com,"11143 Park Squares\nSamanthatown, UT 97073",SandyBrown,33.256335,13.858062,37.780265,5.920580,725.584814
65,kyang@diaz.org,"223 Love Trail Suite 831\nPort Jeffrey, IN 46849",OliveDrab,34.374258,14.802394,37.157624,5.377594,765.518462
157,asilva@yahoo.com,USNV Johnson\nFPO AP 19026,Wheat,34.603311,12.207298,34.298495,5.920580,744.221867
205,jeffrey54@mcdonald-williams.com,"297 Francis Valley\nSouth Lindsey, NY 13669-5367",Gainsboro,34.967610,13.919494,37.952013,5.066697,712.396327
368,rhonda01@gmail.com,"939 Watson Run\nStaceyberg, VT 58376-0454",Orchid,34.385820,12.729720,36.232110,5.705941,708.935185

In [65]:
data.iloc[50, 7], data.iloc[65, 7], data.iloc[157, 7], data.iloc[205, 7], data.iloc[368, 7] = 705.7271533863172, 705.7271533863172, 705.7271533863172, 705.7271533863172, 705.7271533863172
data.iloc[50, 7], data.iloc[65, 7], data.iloc[157, 7], data.iloc[205, 7], data.iloc[368, 7]

(705.7271533863172,
 705.7271533863172,
 705.7271533863172,
 705.7271533863172,
 705.7271533863172)

In [66]:
data[data['Yearly Amount Spent'] < 288.6249512402365]

,Email,Address,Avatar,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
225,alexandra26@summers-davis.com,Unit 7032 Box 7016\nDPO AE 44749-2992,Navy,32.836941,10.256549,36.143908,1.136371,256.670582
299,morganorozco@hotmail.com,"0001 Mack Mill\nNorth Jennifer, NE 42021-5936",LightPink,30.492537,11.562936,35.976565,1.481617,282.471246
303,brandon77@richardson.com,"109 Jessica Manor\nNorth Patriciashire, PR 84726",GhostWhite,30.816201,11.851399,36.925043,1.136371,266.086341
415,brian51@cook.info,"0508 Terrance Cliff\nRebekahtown, NC 48724-8308",SaddleBrown,31.517122,10.745189,38.791235,1.428824,275.918421

In [67]:
data.iloc[225, 7], data.iloc[299, 7], data.iloc[303, 7], data.iloc[415, 7] = 288.6249512402365, 288.6249512402365, 288.6249512402365, 288.6249512402365
data.iloc[225, 7], data.iloc[299, 7], data.iloc[303, 7], data.iloc[415, 7]

(288.6249512402365, 288.6249512402365, 288.6249512402365, 288.6249512402365)

In [68]:
data

,Email,Address,Avatar,Avg. Session Length,Time on App,Time on Website,Length of Membership,Yearly Amount Spent
0,mstephenson@fernandez.com,"835 Frank Tunnel\nWrightmouth, MI 82180-9605",Violet,34.497268,12.655651,39.577668,4.082621,587.951054
1,hduke@hotmail.com,"4547 Archer Common\nDiazchester, CA 06566-8576",DarkGreen,31.926272,11.109461,37.268959,2.664034,392.204933
2,pallen@yahoo.com,"24645 Valerie Unions Suite 582\nCobbborough, D...",Bisque,33.000915,11.330278,37.110597,4.104543,487.547505
3,riverarebecca@gmail.com,"1414 David Throughway\nPort Jason, OH 22070-1220",SaddleBrown,34.305557,13.717514,36.721283,3.120179,581.852344
4,mstephens@davidson-herman.com,"14023 Rodriguez Passage\nPort Jacobville, PR 3...",MediumAquaMarine,33.330673,12.795189,37.536653,4.446308,599.406092
...,...,...,...,...,...,...,...,...
495,lewisjessica@craig-evans.com,"4483 Jones Motorway Suite 872\nLake Jamiefurt,...",Tan,33.237660,13.566160,36.417985,3.746573,573.847438
496,katrina56@gmail.com,"172 Owen Divide Suite 497\nWest Richard, CA 19320",PaleVioletRed,34.702529,11.695736,37.190268,3.576526,529.049004
497,dale88@hotmail.com,"0787 Andrews Ranch Apt. 633\nSouth Chadburgh, ...",Cornsilk,32.646777,11.499409,38.332576,4.958264,551.620145
498,cwilson@hotmail.com,"680 Jennifer Lodge Apt. 808\nBrendachester, TX...",Teal,33.322501,12.391423,36.840086,2.336485,456.469510
499,hannahwilson@davidson.com,49791 Rachel Heights Apt. 898\nEast Drewboroug...,DarkMagenta,33.715981,12.418808,35.771016,2.735160,497.778642